## Switches
set_property PACKAGE_PIN V17 [get_ports selection[0]]					
	set_property IOSTANDARD LVCMOS33 [get_ports selection[0]]
set_property PACKAGE_PIN V16 [get_ports selection[1]]					
	set_property IOSTANDARD LVCMOS33 [get_ports selection[1]]
set_property PACKAGE_PIN W16 [get_ports selection[2]]					
	set_property IOSTANDARD LVCMOS33 [get_ports selection[2]]
##set_property PACKAGE_PIN W17 [get_ports {sw[3]}]					
#	#set_property IOSTANDARD LVCMOS33 [get_ports {sw[3]}]
set_property PACKAGE_PIN W15 [get_ports b[0]]					
	set_property IOSTANDARD LVCMOS33 [get_ports b[0]]
set_property PACKAGE_PIN V15 [get_ports b[1]]					
	set_property IOSTANDARD LVCMOS33 [get_ports b[1]]
set_property PACKAGE_PIN W14 [get_ports b[2]]					
	set_property IOSTANDARD LVCMOS33 [get_ports b[2]]
set_property PACKAGE_PIN W13 [get_ports b[3]]					
	set_property IOSTANDARD LVCMOS33 [get_ports b[3]]
set_property PACKAGE_PIN V2 [get_ports b[4]]					
	set_property IOSTANDARD LVCMOS33 [get_ports b[4]]
set_property PACKAGE_PIN T3 [get_ports b[5]]					
	set_property IOSTANDARD LVCMOS33 [get_ports b[5]]
set_property PACKAGE_PIN T2 [get_ports a[0]]					
	set_property IOSTANDARD LVCMOS33 [get_ports a[0]]
set_property PACKAGE_PIN R3 [get_ports a[1]]					
	set_property IOSTANDARD LVCMOS33 [get_ports a[1]]
set_property PACKAGE_PIN W2 [get_ports a[2]]					
	set_property IOSTANDARD LVCMOS33 [get_ports a[2]]
set_property PACKAGE_PIN U1 [get_ports a[3]]					
	set_property IOSTANDARD LVCMOS33 [get_ports a[3]]
set_property PACKAGE_PIN T1 [get_ports a[4]]					
	set_property IOSTANDARD LVCMOS33 [get_ports a[4]]
set_property PACKAGE_PIN R2 [get_ports a[5]]					
	set_property IOSTANDARD LVCMOS33 [get_ports a[5]]
 

## LEDs
#set_property PACKAGE_PIN U16 [get_ports {LED[0]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {LED[0]}]
#set_property PACKAGE_PIN E19 [get_ports {LED[1]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {LED[1]}]
#set_property PACKAGE_PIN U19 [get_ports {LED[2]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {LED[2]}]
#set_property PACKAGE_PIN V19 [get_ports {LED[3]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {LED[3]}]
#set_property PACKAGE_PIN W18 [get_ports {LED[4]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {LED[4]}]
#set_property PACKAGE_PIN U15 [get_ports {LED[5]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {LED[5]}]
#set_property PACKAGE_PIN U14 [get_ports {LED[6]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {LED[6]}]
#set_property PACKAGE_PIN V14 [get_ports {LED[7]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {LED[7]}]
#set_property PACKAGE_PIN V13 [get_ports {LED[8]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {LED[8]}]
#set_property PACKAGE_PIN V3 [get_ports {LED[9]}]					
#	set_property IOSTANDARD LVCMOS33 [get_ports {LED[9]}]
set_property PACKAGE_PIN W3 [get_ports o[0]]					
	set_property IOSTANDARD LVCMOS33 [get_ports o[0]]
set_property PACKAGE_PIN U3 [get_ports o[1]]					
	set_property IOSTANDARD LVCMOS33 [get_ports o[1]]
set_property PACKAGE_PIN P3 [get_ports o[2]]					
	set_property IOSTANDARD LVCMOS33 [get_ports o[2]]
set_property PACKAGE_PIN N3 [get_ports o[3]]					
	set_property IOSTANDARD LVCMOS33 [get_ports o[3]]
set_property PACKAGE_PIN P1 [get_ports o[4]]					
	set_property IOSTANDARD LVCMOS33 [get_ports o[4]]
set_property PACKAGE_PIN L1 [get_ports o[5]]					
	set_property IOSTANDARD LVCMOS33 [get_ports o[5]]
	
	
