set_property PACKAGE_PIN V17 [get_ports {in1}]
    set_property IOSTANDARD LVCMOS33 [get_ports in1]
set_property PACKAGE_PIN V16 [get_ports in2]
    set_property IOSTANDARD LVCMOS33 [get_ports in2]
set_property PACKAGE_PIN U16 [get_ports out1] 
    set_property IOSTANDARD LVCMOS33 [get_ports out1]